### ISSUE TITLE
2D mood engineering update and classification model for mood of tracks

### ISSUE THREAD

**Issue by ghraciella** [ghraciella/mood_music_recommendation_system#48]
# Description

- 2D mood engineering update and classification model for mood of tracks  in order to proceed with main recommendation model
- already done for 2d : (valence + energy), just need to fix the ordering
- classification model to train & predict mood labels and genre for tracks   

# Task List
- [x] dataset : re-engineering 2-D mood to be more robust (i.e other relevant mood labels, multi-mood labels?!)
- [x] 2-D mood classification model and genre/main-genre
- [x] evaluation of classifier
